### ISSUE TITLE
SearchCurrentWord - Undefined variable: #

### ISSUE THREAD

**Issue by x41lakazam** [coderifous/working-set.vim#1]
Hey, I have a (probably stupid) error when trying to search for a word, here is trace with associated source code. 

Error detected while processing function <SNR>83_SearchCurrentWord:
```
func! s:SearchCurrentWord()
  let wordUnderCursor = expand("<cword>")
  call s:SearchWithOptions(wordUnderCursor, #{ whole_word: v:true })
endfunc
```

E121: Undefined variable: #

```
command! -nargs=1 WSw call s:SearchWithOptions(<f-args>, #{ whole_word: v:true })
```

```
func! s:SearchWithOptions(term, options)
  echomsg "WS Search: " . json_encode(a:options) . " " . a:term
  call s:SendMsg("search_changed", #{ args: a:term, options: a:options })
endfunc
```
E116: Invalid arguments for function <SNR>83_SearchWithOptions

I'm running vim8 on arch linux.

**Comment by coderifous** [comment]
Hi!  Sorry I didn't notice this issue for so long.

That code is using the ["literal dictionary" syntax](https://vimhelp.org/eval.txt.html#literal-Dict), which was apparently introduced in Vim 8.1.1705 around July 2019.

I think it will work if you update your Vim - however the code for this plugin doesn't necessarily need to use literal dict syntax, and I didn't realize it was so new in Vim.  I think it will make sense to not use them in this plugin.

**Comment by coderifous** [comment]
I just pushed a minor version bump to `master` that should resolve the issue: 2ab955f

Thanks again for the note!
